### ISSUE TITLE
Ayuda con html de la web

### ISSUE THREAD

**Issue by SamuelG43** [SamuelG43/Nuevo-Scripting#1]
Se necesita ayuda con la pagina de html, no esta repondiendo bien a las interacciones de los usuarios 

🦩

**Comment by xaca** [comment]
Hola @SamuelG43,

Yo te puedo ayudar, ya te envio la solución

💪

**Comment by SamuelG43** [comment]
@xaca R

**Comment by xaca** [comment]
Solo queda pendiente configurar github pages, entrar por settings/githup pages/ activar la publicaciòn de la rama principal

**Comment by SamuelG43** [comment]
Ya quedó bien
